name: kibot

on: [push]
  # push:
  #   paths:
  #   - '**.sch'
  #   - '**.kicad_pcb'
  # pull_request:
  #   paths:
  #     - '**.sch'
  #     - '**.kicad_pcb'

jobs:
  example:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mirte-master

    steps:
    - run: ls
    # - run: cd mirte-master
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2
      with:
        # Required - kibot config file
        config: kibot_generated.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: 'mirte-master.sch'
        # optional - PCB design file
        board: 'mirte-master.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output
