name: kibot

on: [push]
  
jobs:
  
  example:
    permissions:
    # Required to upload/save artifact, otherwise you'll get
    # "Error: Resource not accessible by integration"
      contents: write
      # Required to post comment, otherwise you'll get
      # "Error: Resource not accessible by integration"
      pull-requests: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [mirte-master, mirte-pioneer, mirte-master-bottom]
    environment: kibot
    # defaults:
    #   run:
        # working-directory: mirte-master

    steps:
    # - run: ls
    # - run: cd mirte-master
    - if: matrix.project == 'mirte-pioneer'
      run: echo "SCH_NAME=mirte_combination" >> $GITHUB_ENV
    - if: matrix.project != 'mirte-pioneer'
      run: echo "SCH_NAME=${{ matrix.project }}" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k7 
      with:
        # Required - kibot config file
        config: mirte-master/kibot_generated.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: '${{ matrix.project }}/${{ env.SCH_NAME }}.kicad_sch'
        # optional - PCB design file
        board: 'mirte-master/mirte-master.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.project }}
        path: output